[package]
name = "xi-tinkerer-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "xi_tinkerer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module", "abi3-py311"] }
dats = { git = "https://github.com/sruon/xi-tinkerer.git", branch = "unstable", package = "dats" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
